export interface Servico {
  nome: string
  descricao: string
  preco: string
  duracao: string
  categoria: Categoria
  variantes?: { nome: string; preco: string }[]
  promocao?: string
}

export type Categoria =
  | "corte-finalizacao"
  | "quimica-tratamento"
  | "manicure-pedicure"
  | "alongamento"
  | "olhar-face"
  | "bem-estar"
  | "maquiagem"
  | "depilacao"
  | "penteado"

export interface CategoriaInfo {
  id: Categoria
  nome: string
  descricao: string
  icone: string
}

export const categorias: CategoriaInfo[] = [
  {
    id: "corte-finalizacao",
    nome: "Corte & Finalização",
    descricao: "Cortes personalizados e finalizações impecáveis para todos os estilos.",
    icone: "Scissors",
  },
  {
    id: "quimica-tratamento",
    nome: "Química & Tratamento",
    descricao: "Progressivas, selagens, mechas, colorações e tratamentos capilares profundos.",
    icone: "Sparkles",
  },
  {
    id: "manicure-pedicure",
    nome: "Manicure & Pedicure",
    descricao: "Do tradicional ao magnífico, cuidamos das suas unhas com carinho.",
    icone: "Paintbrush",
  },
  {
    id: "alongamento",
    nome: "Alongamento de Unhas",
    descricao: "Fibra ou gel, formatos variados, com esmaltação tradicional ou em gel.",
    icone: "Flower2",
  },
  {
    id: "olhar-face",
    nome: "Olhar & Face",
    descricao: "Extensão de cílios, design de sobrancelha, henna e dermaplaning.",
    icone: "Eye",
  },
  {
    id: "bem-estar",
    nome: "Bem-Estar",
    descricao: "Spa dos pés, plástica dos pés e massagens relaxantes.",
    icone: "Heart",
  },
  {
    id: "maquiagem",
    nome: "Maquiagem",
    descricao: "Make completa, noiva e truque de make para todas as ocasiões.",
    icone: "Palette",
  },
  {
    id: "depilacao",
    nome: "Depilação",
    descricao: "Depilação com cera em todas as regiões, com conforto e qualidade.",
    icone: "Wind",
  },
  {
    id: "penteado",
    nome: "Penteado",
    descricao: "Penteados para ocasiões especiais, do clássico ao moderno.",
    icone: "Crown",
  },
]

export const servicos: Servico[] = [
  // ============ CORTE & FINALIZAÇÃO ============
  {
    nome: "Design de Corte Feminino",
    descricao: "Cortes sob medida para realçar sua beleza. Técnicas atualizadas, profissionais experientes. Clássico, moderno, repicado, em camadas ou assimétrico.",
    preco: "R$ 100",
    duracao: "1h",
    categoria: "corte-finalizacao",
  },
  {
    nome: "Design de Corte Feminino Infantil",
    descricao: "Corte delicado e encantador para pequenas clientes de até 10 anos, realçando a beleza natural das crianças.",
    preco: "R$ 86",
    duracao: "1h",
    categoria: "corte-finalizacao",
  },
  {
    nome: "Corte Franja",
    descricao: "Franja personalizada que realça os traços faciais com visual moderno e versátil.",
    preco: "R$ 46",
    duracao: "40min",
    categoria: "corte-finalizacao",
  },
  {
    nome: "Design de Corte Especial",
    descricao: "Corte personalizado com higienização especial que limpa e revitaliza os fios. Experiência relaxante.",
    preco: "R$ 104",
    duracao: "1h",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Cabelo Longo+", preco: "R$ 108" },
    ],
  },
  {
    nome: "Escova Clássica",
    descricao: "Fios lisos, sedosos e com brilho radiante. Técnicas profissionais para um penteado liso e deslumbrante.",
    preco: "R$ 60",
    duracao: "50min",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Curto", preco: "R$ 60" },
      { nome: "Médio", preco: "R$ 70" },
      { nome: "Longo", preco: "R$ 80" },
      { nome: "Extra Longo", preco: "R$ 90" },
    ],
  },
  {
    nome: "Escova Modelada/Babyliss",
    descricao: "Transformação com babyliss para ondas suaves, cachos definidos ou look glamouroso.",
    preco: "R$ 70",
    duracao: "1h",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Curto", preco: "R$ 70" },
      { nome: "Médio", preco: "R$ 80" },
      { nome: "Longo", preco: "R$ 90" },
      { nome: "Extra Longo", preco: "R$ 100" },
    ],
  },
  {
    nome: "Escova Modelada/Babyliss Preso",
    descricao: "Babyliss com penteado preso para um visual elegante e versátil.",
    preco: "R$ 85",
    duracao: "50min",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Curto", preco: "R$ 85" },
      { nome: "Médio", preco: "R$ 100" },
      { nome: "Longo", preco: "R$ 115" },
      { nome: "Extra Longo", preco: "R$ 130" },
    ],
  },
  {
    nome: "Escova Torcida",
    descricao: "Escova com efeito torcido para um visual diferenciado e cheio de personalidade.",
    preco: "R$ 80",
    duracao: "50min",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Curto", preco: "R$ 80" },
      { nome: "Médio", preco: "R$ 90" },
      { nome: "Longo", preco: "R$ 100" },
      { nome: "Extra Longo", preco: "R$ 110" },
    ],
  },
  {
    nome: "Escova Chapinha",
    descricao: "Cabelos lisos, sedosos e com brilho impecável com prancha de alta qualidade.",
    preco: "R$ 70",
    duracao: "50min",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Curto", preco: "R$ 70" },
      { nome: "Médio", preco: "R$ 80" },
      { nome: "Longo", preco: "R$ 90" },
      { nome: "Extra Longo", preco: "R$ 100" },
    ],
  },
  {
    nome: "Chapinha (sem higienização)",
    descricao: "Chapar o cabelo sem higienização, para um liso rápido.",
    preco: "R$ 40",
    duracao: "40min",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Curto", preco: "R$ 40" },
      { nome: "Médio", preco: "R$ 50" },
      { nome: "Longo", preco: "R$ 60" },
      { nome: "Extra Longo", preco: "R$ 70" },
    ],
  },
  {
    nome: "Design de Corte & Escova Clássica",
    descricao: "Corte personalizado + escova clássica para um visual completo e impecável.",
    preco: "R$ 159",
    duracao: "1h30",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Longo+", preco: "R$ 167" },
    ],
  },
  {
    nome: "Design de Corte & Escova Modelada/Babyliss",
    descricao: "Corte + babyliss para cachos definidos ou ondas glamourosas.",
    preco: "R$ 169",
    duracao: "1h30",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Longo+", preco: "R$ 177" },
    ],
  },
  {
    nome: "Design de Corte & Escova Torcida",
    descricao: "Corte + escova torcida para um look cheio de atitude.",
    preco: "R$ 179",
    duracao: "1h30",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Longo+", preco: "R$ 187" },
    ],
  },
  {
    nome: "Design de Corte Especial & Escova Clássica",
    descricao: "Corte especial com higienização + escova clássica.",
    preco: "R$ 171",
    duracao: "1h30",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Longo+", preco: "R$ 179" },
    ],
  },
  {
    nome: "Design de Corte Especial & Escova Modelada/Babyliss",
    descricao: "Corte especial + babyliss para um look glamouroso completo.",
    preco: "R$ 181",
    duracao: "1h30",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Longo+", preco: "R$ 189" },
    ],
  },
  {
    nome: "Design de Corte Especial & Escova Torcida",
    descricao: "Corte especial + escova torcida para um visual único.",
    preco: "R$ 191",
    duracao: "1h30",
    categoria: "corte-finalizacao",
    variantes: [
      { nome: "Longo+", preco: "R$ 199" },
    ],
  },

  // ============ QUÍMICA & TRATAMENTO ============
  {
    nome: "Escova Progressiva",
    descricao: "Tratamento revolucionário para cabelos lisos, brilhantes e disciplinados. Atua no interior dos fios eliminando o frizz.",
    preco: "R$ 300",
    duracao: "3h",
    categoria: "quimica-tratamento",
    variantes: [
      { nome: "Curto", preco: "R$ 300" },
      { nome: "Médio", preco: "R$ 360" },
      { nome: "Longo", preco: "R$ 420" },
      { nome: "Extra Longo", preco: "R$ 480" },
    ],
  },
  {
    nome: "Escova Progressiva Orgânica",
    descricao: "Progressiva com fórmula orgânica. Cabelos lisos e sem frizz com ingredientes naturais.",
    preco: "R$ 300",
    duracao: "3h",
    categoria: "quimica-tratamento",
    variantes: [
      { nome: "Curto", preco: "R$ 300" },
      { nome: "Médio", preco: "R$ 360" },
      { nome: "Longo", preco: "R$ 420" },
      { nome: "Extra Longo", preco: "R$ 480" },
    ],
  },
  {
    nome: "Progressiva Franja",
    descricao: "Alisamento apenas da franja.",
    preco: "R$ 80",
    duracao: "45min",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Progressiva Orgânica Franja",
    descricao: "Alisamento orgânico apenas da franja.",
    preco: "R$ 100",
    duracao: "1h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Progressiva Raiz",
    descricao: "Alisamento apenas da raiz para retoque.",
    preco: "R$ 250",
    duracao: "1h20",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Progressiva Orgânica Raiz",
    descricao: "Alisamento orgânico apenas da raiz.",
    preco: "R$ 250",
    duracao: "1h20",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Selagem",
    descricao: "Fórmula nutritiva que reduz volume e alinha as cutículas. Cabelos disciplinados e saudáveis.",
    preco: "R$ 250",
    duracao: "3h",
    categoria: "quimica-tratamento",
    variantes: [
      { nome: "Curto", preco: "R$ 250" },
      { nome: "Médio", preco: "R$ 310" },
      { nome: "Longo", preco: "R$ 370" },
      { nome: "Extra Longo", preco: "R$ 430" },
    ],
  },
  {
    nome: "Selagem Orgânica",
    descricao: "Selagem com fórmula orgânica. Redução de volume e alinhamento com ingredientes naturais.",
    preco: "R$ 300",
    duracao: "3h",
    categoria: "quimica-tratamento",
    variantes: [
      { nome: "Curto", preco: "R$ 300" },
      { nome: "Médio", preco: "R$ 360" },
      { nome: "Longo", preco: "R$ 420" },
      { nome: "Extra Longo", preco: "R$ 480" },
    ],
  },
  {
    nome: "Selagem Franja",
    descricao: "Selagem apenas na franja para alinhar e reduzir volume.",
    preco: "R$ 80",
    duracao: "45min",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Selagem Orgânica Franja",
    descricao: "Selagem orgânica apenas na franja.",
    preco: "R$ 100",
    duracao: "1h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Selagem Raiz",
    descricao: "Selagem apenas na raiz para retoque.",
    preco: "R$ 250",
    duracao: "3h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Selagem Orgânica Raiz",
    descricao: "Selagem orgânica apenas na raiz.",
    preco: "R$ 300",
    duracao: "3h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Botox Capilar",
    descricao: "Tratamento poderoso que revitaliza e rejuvenesce os cabelos. Preenche as fibras capilares e elimina o frizz.",
    preco: "R$ 250",
    duracao: "3h",
    categoria: "quimica-tratamento",
    variantes: [
      { nome: "Curto", preco: "R$ 250" },
      { nome: "Médio", preco: "R$ 300" },
      { nome: "Longo", preco: "R$ 350" },
      { nome: "Extra Longo", preco: "R$ 380" },
    ],
  },
  {
    nome: "Mechas/Luzes Keune",
    descricao: "Combo Descoloração com hidratação nutritiva ou reconstrução com escova. Marca Keune premium.",
    preco: "R$ 500",
    duracao: "4h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Mechas/Luzes London",
    descricao: "Combo Descoloração com hidratação nutritiva ou reconstrução com escova. Marca London.",
    preco: "R$ 500",
    duracao: "4h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Mechas Contorno Keune",
    descricao: "Mechas de contorno com Keune. Ilumine seus cabelos com estilo e sofisticação.",
    preco: "R$ 300",
    duracao: "4h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Mechas Contorno London",
    descricao: "Mechas de contorno com London. Efeito iluminado natural.",
    preco: "R$ 250",
    duracao: "4h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Luzes Touca Keune",
    descricao: "Luzes com touca usando Keune. Efeito iluminado uniforme.",
    preco: "R$ 450",
    duracao: "4h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Luzes Touca London",
    descricao: "Luzes com touca usando London. Visual iluminado e natural.",
    preco: "R$ 400",
    duracao: "4h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Coloração Global",
    descricao: "Coloração completa em toda a extensão dos cabelos.",
    preco: "R$ 230",
    duracao: "2h30",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Coloração de Crescimento",
    descricao: "Coloração na raiz para disfarçar o crescimento.",
    preco: "R$ 180",
    duracao: "1h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Aplicação de Coloração Global",
    descricao: "Aplicação de coloração global com tinta trazida pela cliente.",
    preco: "R$ 142",
    duracao: "2h30",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Aplicação de Coloração de Crescimento",
    descricao: "Aplicação de coloração de crescimento com tinta da cliente.",
    preco: "R$ 92",
    duracao: "1h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Matizador",
    descricao: "Matização para neutralizar tons indesejados e realçar a cor.",
    preco: "R$ 160",
    duracao: "30min",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Tonalizante Keune",
    descricao: "Cor intensa e duradoura sem danificar os fios. Marca Keune.",
    preco: "R$ 260",
    duracao: "3h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Tonalizante London",
    descricao: "Cor suave e natural com London. Ampla variedade de tonalidades.",
    preco: "R$ 200",
    duracao: "3h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Tratamento CMC Restore London",
    descricao: "Nutrição intensa e imediata com escova clássica inclusa. Para cabelos secos ou ressecados por química.",
    preco: "R$ 180",
    duracao: "1h",
    categoria: "quimica-tratamento",
    variantes: [
      { nome: "Curto", preco: "R$ 180" },
      { nome: "Médio", preco: "R$ 190" },
      { nome: "Longo", preco: "R$ 200" },
      { nome: "Extra Longo", preco: "R$ 210" },
    ],
  },
  {
    nome: "Aplicação de Tratamento",
    descricao: "Aplicação de tratamento com produto trazido pela cliente.",
    preco: "R$ 80",
    duracao: "1h",
    categoria: "quimica-tratamento",
  },
  {
    nome: "Higienização",
    descricao: "Limpeza suave com produtos de alta qualidade. Remove impurezas, resíduos e oleosidade.",
    preco: "R$ 36",
    duracao: "30min",
    categoria: "quimica-tratamento",
    variantes: [
      { nome: "Padrão", preco: "R$ 36" },
      { nome: "Longo+", preco: "R$ 44" },
    ],
  },
  {
    nome: "Higienização Especial",
    descricao: "Tratamento carinhoso com produtos premium que cuidam dos fios com todo cuidado.",
    preco: "R$ 42",
    duracao: "30min",
    categoria: "quimica-tratamento",
    variantes: [
      { nome: "Padrão", preco: "R$ 42" },
      { nome: "Longo+", preco: "R$ 50" },
    ],
  },
  {
    nome: "After Color Keune",
    descricao: "Hidratação pós-coloração Keune para manter a cor vibrante e os fios saudáveis.",
    preco: "R$ 40",
    duracao: "20min",
    categoria: "quimica-tratamento",
  },

  // ============ MANICURE & PEDICURE ============
  {
    nome: "Manicure - Esmaltação",
    descricao: "Esmaltação das unhas das mãos com variedade de cores, incluindo corte, lixamento e esmaltação. Sem cuticulagem.",
    preco: "R$ 23,20",
    duracao: "40min",
    categoria: "manicure-pedicure",
    promocao: "R$ 27 por R$ 23,20",
  },
  {
    nome: "Pedicure - Esmaltação",
    descricao: "Esmaltação das unhas dos pés com variedade de cores, incluindo corte, lixamento e esmaltação. Sem cuticulagem.",
    preco: "R$ 26,66",
    duracao: "50min",
    categoria: "manicure-pedicure",
    promocao: "R$ 31 por R$ 26,66",
  },
  {
    nome: "Manicure & Pedicure - Esmaltação",
    descricao: "Esmaltação das mãos e pés pelo mesmo profissional. Corte, lixamento e esmaltação. Sem cuticulagem.",
    preco: "R$ 50",
    duracao: "50min",
    categoria: "manicure-pedicure",
    promocao: "R$ 58 por R$ 50",
  },
  {
    nome: "Manicure - Tradicional",
    descricao: "Cuidado completo: corte, cuticulagem, lixamento e esmaltação.",
    preco: "R$ 35",
    duracao: "1h",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Pedicure - Tradicional",
    descricao: "Cuidado completo para os pés: corte, cuticulagem, lixamento e esmaltação.",
    preco: "R$ 40",
    duracao: "1h",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Manicure & Pedicure - Tradicional",
    descricao: "Cuidado completo mãos e pés pelo mesmo profissional.",
    preco: "R$ 70",
    duracao: "2h",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Manicure - Cuticulagem",
    descricao: "Corte, lixamento e cuticulagem, sem esmaltação.",
    preco: "R$ 30",
    duracao: "50min",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Pedicure - Cuticulagem",
    descricao: "Corte, lixamento e cuticulagem dos pés, sem esmaltação.",
    preco: "R$ 35",
    duracao: "1h",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Manicure & Pedicure - Cuticulagem",
    descricao: "Corte, lixamento e cuticulagem das mãos e pés.",
    preco: "R$ 64",
    duracao: "1h50",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Manicure - Magnífica",
    descricao: "Cuidado completo: esfoliação, hidratação, massagem, corte, cuticulagem, lixamento e esmaltação.",
    preco: "R$ 38",
    duracao: "1h10",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Pedicure - Magnífica",
    descricao: "Cuidado completo para os pés: esfoliação, hidratação, massagem, lixador, corte, cuticulagem, lixamento e esmaltação.",
    preco: "R$ 46",
    duracao: "1h20",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Manicure & Pedicure - Magnífica",
    descricao: "Cuidado completo mãos e pés com esfoliação, hidratação e massagem.",
    preco: "R$ 80",
    duracao: "2h",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Manicure - Esmaltação em Gel",
    descricao: "Esmaltação em gel com cuticulagem inclusa. Acabamento impecável e duradouro.",
    preco: "R$ 85",
    duracao: "2h",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Manicure & Pedicure - Esmaltação em Gel",
    descricao: "Esmaltação em gel para mãos e pés com cuticulagem inclusa.",
    preco: "R$ 170",
    duracao: "2h20",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Manicure - Infantil",
    descricao: "Cuidado especial para unhas de crianças até 10 anos.",
    preco: "R$ 14,60",
    duracao: "30min",
    categoria: "manicure-pedicure",
    promocao: "R$ 17 por R$ 14,60",
  },
  {
    nome: "Pedicure - Infantil",
    descricao: "Cuidado especial para pés de crianças até 10 anos.",
    preco: "R$ 16,40",
    duracao: "30min",
    categoria: "manicure-pedicure",
    promocao: "R$ 19 por R$ 16,40",
  },
  {
    nome: "Manicure & Pedicure - Infantil",
    descricao: "Manicure + Pedicure infantil pelo mesmo profissional.",
    preco: "R$ 31",
    duracao: "1h",
    categoria: "manicure-pedicure",
    promocao: "R$ 36 por R$ 31",
  },
  {
    nome: "Adicional Unhas - Francesa",
    descricao: "Acabamento francesinha nas unhas.",
    preco: "R$ 5",
    duracao: "10min",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Adicional Unhas - Adesivo",
    descricao: "Adicional de decoração com adesivo.",
    preco: "R$ 5",
    duracao: "20min",
    categoria: "manicure-pedicure",
  },
  {
    nome: "Adicional Unhas - Top Coat",
    descricao: "Top coat para mais durabilidade e resistência à esmaltação.",
    preco: "R$ 10",
    duracao: "20min",
    categoria: "manicure-pedicure",
  },

  // ============ ALONGAMENTO DE UNHAS ============
  {
    nome: "Alongamento Fibra Tradicional",
    descricao: "Unhas longas e resistentes com fibra tradicional formato quadrado.",
    preco: "R$ 190",
    duracao: "3h",
    categoria: "alongamento",
  },
  {
    nome: "Along. Fibra Tradicional + Esmaltação em Gel",
    descricao: "Fibra tradicional com esmaltação em gel para brilho intenso e durabilidade.",
    preco: "R$ 240",
    duracao: "3h20",
    categoria: "alongamento",
  },
  {
    nome: "Alongamento Fibra Formatos",
    descricao: "Unhas com fibra em diferentes formatos personalizados para cada cliente.",
    preco: "R$ 220",
    duracao: "3h",
    categoria: "alongamento",
  },
  {
    nome: "Along. Fibra Formatos + Esmaltação em Gel",
    descricao: "Fibra em formatos variados com esmaltação em gel.",
    preco: "R$ 260",
    duracao: "3h20",
    categoria: "alongamento",
  },
  {
    nome: "Along. Fibra Formatos + Encapsulada",
    descricao: "Fibra formatos com encapsulada para resultado único e duradouro.",
    preco: "R$ 240",
    duracao: "3h20",
    categoria: "alongamento",
  },
  {
    nome: "Along. Fibra Formatos + Francesa Reversa",
    descricao: "Fibra formatos com francesa reversa. Visual sofisticado e elegante.",
    preco: "R$ 260",
    duracao: "3h20",
    categoria: "alongamento",
  },
  {
    nome: "Manutenção Fibra Formatos",
    descricao: "Manutenção do alongamento de fibra formatos. Unhas sempre bonitas.",
    preco: "R$ 190",
    duracao: "3h",
    categoria: "alongamento",
  },
  {
    nome: "Manutenção Fibra Formatos + Esmaltação em Gel",
    descricao: "Manutenção com esmaltação em gel para unhas deslumbrantes.",
    preco: "R$ 220",
    duracao: "3h",
    categoria: "alongamento",
  },
  {
    nome: "Manutenção Fibra Formatos + Encapsulada",
    descricao: "Manutenção com encapsulada para resultado exclusivo e resistente.",
    preco: "R$ 210",
    duracao: "3h",
    categoria: "alongamento",
  },
  {
    nome: "Manutenção Fibra Formatos + Francesa Reversa",
    descricao: "Manutenção com francesa reversa. Visual refinado e delicado.",
    preco: "R$ 220",
    duracao: "3h20",
    categoria: "alongamento",
  },
  {
    nome: "Alongamento em Gel Tradicional",
    descricao: "Unhas longas e duráveis com gel tradicional.",
    preco: "R$ 160",
    duracao: "3h",
    categoria: "alongamento",
  },
  {
    nome: "Manutenção Unha em Gel Tradicional",
    descricao: "Manutenção do alongamento em gel tradicional.",
    preco: "R$ 130",
    duracao: "3h",
    categoria: "alongamento",
  },
  {
    nome: "Alongamento em Gel Formatos",
    descricao: "Unhas em gel com formatos variados e personalizados.",
    preco: "R$ 180",
    duracao: "3h",
    categoria: "alongamento",
  },
  {
    nome: "Along. em Gel Formatos + Esmaltação em Gel",
    descricao: "Gel formatos com esmaltação em gel para unhas deslumbrantes.",
    preco: "R$ 210",
    duracao: "3h20",
    categoria: "alongamento",
  },
  {
    nome: "Manutenção Unha em Gel Formatos",
    descricao: "Manutenção do alongamento em gel formatos.",
    preco: "R$ 165",
    duracao: "3h",
    categoria: "alongamento",
  },

  // ============ OLHAR & FACE ============
  {
    nome: "Cílios Clássico (Fio a Fio)",
    descricao: "Cílios deslumbrantes e naturais com técnica fio a fio. Fios delicados, discretos e alongados.",
    preco: "R$ 150",
    duracao: "1h",
    categoria: "olhar-face",
  },
  {
    nome: "Cílios - Volume Russo",
    descricao: "Efeito de volume intenso. Cílios mais cheios, longos e glamorosos. Olhar que cativa.",
    preco: "R$ 179",
    duracao: "1h",
    categoria: "olhar-face",
  },
  {
    nome: "Cílios - Volume Híbrido",
    descricao: "Combina fios individuais com cílios em leque. Resultado cheio de glamour natural.",
    preco: "R$ 190",
    duracao: "1h",
    categoria: "olhar-face",
  },
  {
    nome: "Cílios - Volume Power 30+",
    descricao: "Volume power com duração de 30 dias ou mais. Não precisa de manutenção.",
    preco: "R$ 260",
    duracao: "2h30",
    categoria: "olhar-face",
  },
  {
    nome: "Cílios - Volume Mega Brasileiro 30+",
    descricao: "Volume mega brasileiro com duração prolongada de 30 dias ou mais.",
    preco: "R$ 260",
    duracao: "2h30",
    categoria: "olhar-face",
  },
  {
    nome: "Cílios 30+",
    descricao: "Extensão de cílios com duração prolongada de 30 dias ou mais.",
    preco: "R$ 180",
    duracao: "2h",
    categoria: "olhar-face",
  },
  {
    nome: "Cílios em Tela",
    descricao: "Técnica inovadora com resultado natural e volumoso. Duração de 5 a 10 dias.",
    preco: "R$ 60",
    duracao: "15min",
    categoria: "olhar-face",
  },
  {
    nome: "Cílios Tufinho",
    descricao: "Técnica delicada para volume e comprimento. Efeito encantador. Duração 15 a 20 dias.",
    preco: "R$ 90",
    duracao: "30min",
    categoria: "olhar-face",
  },
  {
    nome: "Design de Sobrancelha",
    descricao: "Design personalizado que realça a expressão do olhar.",
    preco: "R$ 50",
    duracao: "30min",
    categoria: "olhar-face",
  },
  {
    nome: "Design de Sobrancelha + Refectocil",
    descricao: "Design com coloração dos pêlos. Ideal para pêlos brancos ou claros. Duração 20 a 25 dias.",
    preco: "R$ 80",
    duracao: "50min",
    categoria: "olhar-face",
  },
  {
    nome: "Aplicação de Henna",
    descricao: "Aplicação de henna para sobrancelhas.",
    preco: "R$ 20",
    duracao: "30min",
    categoria: "olhar-face",
  },
  {
    nome: "Dermaplaning",
    descricao: "Remoção de pêlos faciais e células mortas para uma pele suave e radiante.",
    preco: "R$ 130",
    duracao: "1h30",
    categoria: "olhar-face",
  },

  // ============ BEM-ESTAR ============
  {
    nome: "Spa dos Pés - Detox",
    descricao: "Pastilha de carvão vegetal ativado com óleo de copaíba. Ação antibacteriana e antifungicida.",
    preco: "R$ 114",
    duracao: "45min",
    categoria: "bem-estar",
  },
  {
    nome: "Spa dos Pés - Jelly Calm",
    descricao: "Geléia terapêutica que se transforma com água e movimentos dos pés. Experiência única.",
    preco: "R$ 100",
    duracao: "50min",
    categoria: "bem-estar",
  },
  {
    nome: "Spa dos Pés - Terapêutico",
    descricao: "Esferas efervescentes com ação terapêutica. Renovação celular e relaxamento.",
    preco: "R$ 126",
    duracao: "50min",
    categoria: "bem-estar",
  },
  {
    nome: "Spa dos Pés & Pedicure Magnífica - Detox",
    descricao: "Spa detox + pedicure completa com esfoliação, hidratação e massagem.",
    preco: "R$ 149",
    duracao: "2h",
    categoria: "bem-estar",
  },
  {
    nome: "Spa dos Pés & Pedicure Magnífica - Jelly Calm",
    descricao: "Spa jelly calm + pedicure completa.",
    preco: "R$ 139",
    duracao: "2h",
    categoria: "bem-estar",
  },
  {
    nome: "Spa dos Pés & Pedicure Magnífica - Terapêutico",
    descricao: "Spa terapêutico + pedicure completa.",
    preco: "R$ 159",
    duracao: "2h",
    categoria: "bem-estar",
  },
  {
    nome: "Plástica dos Pés",
    descricao: "Tratamento específico para pés ressecados, devolvendo maciez e hidratação.",
    preco: "R$ 85",
    duracao: "1h",
    categoria: "bem-estar",
  },
  {
    nome: "Plástica dos Pés - Terapêutico",
    descricao: "Plástica dos pés com máscara de argila terapêutica.",
    preco: "R$ 118",
    duracao: "1h20",
    categoria: "bem-estar",
  },
  {
    nome: "Plástica dos Pés & Pedicure - Esmaltação",
    descricao: "Plástica dos pés + pedicure com esmaltação (sem cuticulagem).",
    preco: "R$ 116",
    duracao: "1h50",
    categoria: "bem-estar",
  },
  {
    nome: "Plástica dos Pés & Pedicure - Cuticulagem",
    descricao: "Plástica dos pés + pedicure com cuticulagem (sem esmaltação).",
    preco: "R$ 119",
    duracao: "2h",
    categoria: "bem-estar",
  },
  {
    nome: "Plástica dos Pés & Pedicure - Tradicional",
    descricao: "Plástica + pedicure tradicional com corte, cuticulagem, lixamento e esmaltação.",
    preco: "R$ 121",
    duracao: "2h",
    categoria: "bem-estar",
  },
  {
    nome: "Plástica dos Pés & Pedicure - Magnífica",
    descricao: "Plástica + pedicure completa com esfoliação, hidratação e massagem.",
    preco: "R$ 128",
    duracao: "2h",
    categoria: "bem-estar",
  },
  {
    nome: "Plástica dos Pés & Pedicure - Terapêutico",
    descricao: "Plástica com máscara de argila + pedicure completa.",
    preco: "R$ 149",
    duracao: "2h10",
    categoria: "bem-estar",
  },
  {
    nome: "Massageador Elétrico",
    descricao: "Massagem relaxante nos pés com massageador elétrico.",
    preco: "R$ 10",
    duracao: "15min",
    categoria: "bem-estar",
  },

  // ============ MAQUIAGEM ============
  {
    nome: "Maquiagem Completa",
    descricao: "Maquiagem completa com cílios para realçar sua beleza em qualquer ocasião.",
    preco: "R$ 200",
    duracao: "1h",
    categoria: "maquiagem",
  },
  {
    nome: "Maquiagem Noiva",
    descricao: "Make especial para noivas. Visual que ressalta naturalidade e elegância no grande dia.",
    preco: "R$ 240",
    duracao: "1h20",
    categoria: "maquiagem",
  },
  {
    nome: "Truke de Make",
    descricao: "Make rápida com cílios para um visual renovado em menos tempo.",
    preco: "R$ 170",
    duracao: "50min",
    categoria: "maquiagem",
  },

  // ============ DEPILAÇÃO ============
  {
    nome: "Depilação de Buço",
    descricao: "Depilação com cera do buço. Para mulheres incomodadas com pelos no rosto.",
    preco: "R$ 30",
    duracao: "20min",
    categoria: "depilacao",
  },
  {
    nome: "Buço (Cera Fria)",
    descricao: "Depilação do buço com cera fria.",
    preco: "R$ 28",
    duracao: "20min",
    categoria: "depilacao",
  },
  {
    nome: "Costeleta/Queixo",
    descricao: "Depilação na cera de costeleta ou queixo.",
    preco: "R$ 15",
    duracao: "20min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Rosto",
    descricao: "Depilação de rosto feminino completa.",
    preco: "R$ 70",
    duracao: "40min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Axilas",
    descricao: "Depilação com cera das axilas. Pelos crescem mais uniformes e finos.",
    preco: "R$ 38",
    duracao: "30min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Braços Inteiro",
    descricao: "Depilação completa dos braços com cera.",
    preco: "R$ 50",
    duracao: "30min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Meio Braço",
    descricao: "Depilação do meio braço com cera.",
    preco: "R$ 32",
    duracao: "30min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Perna Inteira",
    descricao: "Depilação completa das pernas com cera.",
    preco: "R$ 75",
    duracao: "50min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Meia Perna",
    descricao: "Depilação da meia perna com cera.",
    preco: "R$ 51",
    duracao: "45min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação - Coxa",
    descricao: "Depilação apenas da coxa.",
    preco: "R$ 59",
    duracao: "45min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Virilha",
    descricao: "Depilação com cera da virilha.",
    preco: "R$ 55",
    duracao: "30min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Virilha Completa",
    descricao: "Depilação completa da virilha com cera.",
    preco: "R$ 75",
    duracao: "1h",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Barriga",
    descricao: "Remoção dos pelos acima e abaixo do umbigo.",
    preco: "R$ 48",
    duracao: "30min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Costas",
    descricao: "Depilação completa das costas com cera.",
    preco: "R$ 79",
    duracao: "30min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação de Nádegas",
    descricao: "Depilação das nádegas com cera.",
    preco: "R$ 70",
    duracao: "30min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação Pescoço/Nuca",
    descricao: "Depilação do pescoço ou nuca.",
    preco: "R$ 38",
    duracao: "20min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação - Nariz",
    descricao: "Depilação interna do nariz.",
    preco: "R$ 18",
    duracao: "15min",
    categoria: "depilacao",
  },
  {
    nome: "Depilação Meia Perna + Virilha + Axila",
    descricao: "Combo completo: meia perna, virilha completa e axila.",
    preco: "R$ 155",
    duracao: "1h",
    categoria: "depilacao",
  },

  // ============ PENTEADO ============
  {
    nome: "Penteado",
    descricao: "Penteados criados para realçar sua beleza. Do clássico ao moderno para todas as ocasiões.",
    preco: "R$ 200",
    duracao: "1h20",
    categoria: "penteado",
  },
]